- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bq'
  args: ['load', '--source_format=CSV', '--replace=true', '--autodetect covid-19-data-nytimes:rawdata.us-counties', 'us-counties.csv']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bq'
  args: ['load', '--source_format=CSV', '--replace=true', '--autodetect covid-19-data-nytimes:rawdata.us-states', 'us-states.csv']
