steps:
## update counties table 
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bq'
  args: ['load', '--source_format=CSV', '--replace=true', '--autodetect', 'covid-19-data-nytimes:rawdata.us_counties', 'us-counties.csv']
## update states table
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bq'
  args: ['load', '--source_format=CSV', '--replace=true', '--autodetect', 'covid-19-data-nytimes:rawdata.us_states', 'us-states.csv']
